plugins:
  - id: conforma
    evaluations-dir: "./hack/sampledata/evaluations"

certConfig:
  cert: /certs/gemara-content-service.crt
  key: /certs/gemara-content-service.key

# Add this block to control JWT
jwtAuth:
  enabled: true
  # enabled: false
